services:
  app:
    build: ./TechnicalTask
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080

  postgres:
    build: ./databases/postgresql
    env_file:
      - .env
    volumes:
      - postgresdb:/var/lib/postgresql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 1s
      timeout: 3s
      retries: 10

volumes:
  postgresdb:
