create table if not exists public.users
(
    id         bigint generated by default as identity
        primary key,
    username   varchar(50)             not null
        unique,
    email      varchar(100)            not null
        unique,
    full_name  varchar(100),
    created_at timestamp default now() not null,
    updated_at timestamp default now() not null
);

create table if not exists public.subscription_providers
(
    id    bigint generated by default as identity
        primary key,
    name  varchar(50)    not null
        unique,
    price numeric(10, 2) not null
);

create table if not exists public.subscriptions
(
    id         bigint generated by default as identity
        primary key,
    user_id    bigint                  not null
        constraint fk_subscriptions_user
            references public.users
            on delete cascade,
    service_id bigint                  not null
        constraint fk_subscriptions_service
            references public.subscription_providers
            on delete cascade,
    start_date timestamp default now() not null,
    end_date   timestamp,
    active     boolean   default true,
    constraint uk_subscriptions_user_service
        unique (user_id, service_id)
);

INSERT INTO public.users (username, email, full_name, created_at, updated_at)
VALUES
    ('user1', 'user1@example.com', 'John Doe', '2023-01-01 10:00:00', '2023-01-01 10:00:00'),
    ('user2', 'user2@example.com', 'Jane Smith', '2023-01-02 11:00:00', '2023-01-02 11:00:00'),
    ('user3', 'user3@example.com', 'Alice Johnson', '2023-01-03 12:00:00', '2023-01-03 12:00:00');

INSERT INTO public.subscription_providers (name, price)
VALUES
    ('Netflix', 9.99),
    ('Spotify', 4.99),
    ('YouTube Premium', 11.99),
    ('Disney+', 7.99),
    ('Amazon Prime', 8.99);

INSERT INTO public.subscriptions (user_id, service_id, start_date, end_date, active)
VALUES
    (1, 1, '2023-01-10 00:00:00', '2023-07-10 00:00:00', true),  -- Netflix
    (1, 3, '2023-02-15 00:00:00', NULL, true),                   -- Spotify (без end_date)
    (1, 4, '2023-03-20 00:00:00', '2023-04-20 00:00:00', false), -- YouTube Premium (неактивна)

    (2, 1, '2023-01-05 00:00:00', NULL, true),                   -- Netflix
    (2, 2, '2023-01-10 00:00:00', NULL, true),                   -- Spotify
    (2, 4, '2023-02-01 00:00:00', '2023-08-01 00:00:00', true),  -- Disney+
    (2, 5, '2023-03-01 00:00:00', NULL, false),                  -- Amazon Prime (неактивна)

    (3, 3, '2023-01-15 00:00:00', NULL, true),                   -- YouTube Premium
    (3, 4, '2023-02-20 00:00:00', '2023-05-20 00:00:00', true),  -- Disney+
    (3, 5, '2023-03-10 00:00:00', NULL, true);                   -- Amazon Prime